name: wisevision
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Kayak
      fonts:
        - asset: assets/fonts/KayakSansRegular.otf
        - asset: assets/fonts/KayakSansLight.otf
        - asset: assets/fonts/KayakSansBold.otf

    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700

flutter_native_splash:

  color: "#6255a4"
  image: assets/images/logo.png

  android_12:
    color: "#6255a4"
    image: assets/images/androidLogo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/images/launcher_icon.png"
    background_color: "#hexcode"
    theme_color: "#6255a4"
  



